import './App.css';
import Article from './components/Article';

function App() {
  return (
    <div>
    <Article 
      id="01"
      addressStreet="123 Street" 
      addressCity="Pocatello"
      addressState="Idaho"
      addressZip="10000"
      addressCountry="United States"
      name="Bengal for the Day" 
      location="Big Super Dome" 
      day="01" 
      price="30"
      month="January" 
      time="10:00 AM" 
      year="2022"
      checkIn="10:00 AM"
      eventStart="10:00 AM"
      eventEnd="2:00 PM"
      timeZone="MST"
      repeating="1"
      isWeekly="1"
      isBiWeekly="0"
      repeatingWeekDay="Monday"
      isMonthly="0"
      description="Lorem ipsum dolor, sit amet consectetur adipisicing elit. Illum incidunt dolor voluptatem dolores debitis obcaecati hic mollitia, sequi maxime libero iusto repellendus. Sunt, error eum quisquam necessitatibus mollitia fugit illum?" 
      locationDescription="Lorem ipsum dolor, sit amet consectetur adipisicing elit. Illum incidunt dolor voluptatem dolores debitis obcaecati hic mollitia, sequi maxime libero iusto repellendus. Sunt, error eum quisquam necessitatibus mollitia fugit illum?"
      includedInPrice="Lorem ipsum dolor, sit amet consectetur adipisicing elit. Illum incidunt dolor voluptatem dolores debitis obcaecati hic mollitia, sequi maxime libero iusto repellendus. Sunt, error eum quisquam necessitatibus mollitia fugit illum?"
      /><Article 
      id="02"
      addressStreet="123 Street" 
      addressCity="Pocatello"
      addressState="Idaho"
      addressZip="10000"
      addressCountry="United States"
      name="Bengal for the Day Part 2" 
      location="Big Super Dome" 
      day="01" 
      price="30"
      month="January" 
      time="10:00 AM" 
      year="2022"
      checkIn="10:00 AM"
      eventStart="10:00 AM"
      eventEnd="2:00 PM"
      timeZone="MST"
      repeating="1"
      isWeekly="1"
      isMonthly="0"
      registrationRequired="1"
      description="Lorem ipsum dolor, sit amet consectetur adipisicing elit. Illum incidunt dolor voluptatem dolores debitis obcaecati hic mollitia, sequi maxime libero iusto repellendus. Sunt, error eum quisquam necessitatibus mollitia fugit illum?" 
      locationDescription="Lorem ipsum dolor, sit amet consectetur adipisicing elit. Illum incidunt dolor voluptatem dolores debitis obcaecati hic mollitia, sequi maxime libero iusto repellendus. Sunt, error eum quisquam necessitatibus mollitia fugit illum?"
      includedInPrice="Lorem ipsum dolor, sit amet consectetur adipisicing elit. Illum incidunt dolor voluptatem dolores debitis obcaecati hic mollitia, sequi maxime libero iusto repellendus. Sunt, error eum quisquam necessitatibus mollitia fugit illum?"
      /><Article 
      id="03"
      addressStreet="123 Street" 
      addressCity="Pocatello"
      addressState="Idaho"
      addressZip="10000"
      addressCountry="United States"
      name="Bengal for the Day Part 3" 
      location="Big Super Dome" 
      day="01" 
      price="30"
      month="January" 
      time="10:00 AM" 
      year="2022"
      checkIn="10:00 AM"
      eventStart="10:00 AM"
      eventEnd="2:00 PM"
      timeZone="MST"
      repeating="1"
      isWeekly="1"
      isMonthly="0"
      description="Lorem ipsum dolor, sit amet consectetur adipisicing elit. Illum incidunt dolor voluptatem dolores debitis obcaecati hic mollitia, sequi maxime libero iusto repellendus. Sunt, error eum quisquam necessitatibus mollitia fugit illum?" 
      locationDescription="Lorem ipsum dolor, sit amet consectetur adipisicing elit. Illum incidunt dolor voluptatem dolores debitis obcaecati hic mollitia, sequi maxime libero iusto repellendus. Sunt, error eum quisquam necessitatibus mollitia fugit illum?"
      includedInPrice="Lorem ipsum dolor, sit amet consectetur adipisicing elit. Illum incidunt dolor voluptatem dolores debitis obcaecati hic mollitia, sequi maxime libero iusto repellendus. Sunt, error eum quisquam necessitatibus mollitia fugit illum?"
      /></div>
  );
}

export default App;
